<?php

use Illuminate\Database\Seeder;
use App\IncluyePaquete as IncluyePaquete;

class IncluyePaqueteSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      IncluyePaquete::create([
        'idincluyepaquete'=>1,
        'incluye_id'=>1,
        'paquete_id'=>1
      ]);
      IncluyePaquete::create([
        'idincluyepaquete'=>2,
        'incluye_id'=>12,
        'paquete_id'=>1
      ]);
      IncluyePaquete::create([
        'idincluyepaquete'=>3,
        'incluye_id'=>13,
        'paquete_id'=>1
      ]);
      IncluyePaquete::create([
        'idincluyepaquete'=>4,
        'incluye_id'=>14,
        'paquete_id'=>1
      ]);
      IncluyePaquete::create([
        'idincluyepaquete'=>5,
        'incluye_id'=>15,
        'paquete_id'=>1
      ]);
      IncluyePaquete::create([
        'idincluyepaquete'=>6,
        'incluye_id'=>16,
        'paquete_id'=>3
      ]);
      IncluyePaquete::create([
        'idincluyepaquete'=>7,
        'incluye_id'=>17,
        'paquete_id'=>3
      ]);
      IncluyePaquete::create([
        'idincluyepaquete'=>8,
        'incluye_id'=>18,
        'paquete_id'=>3
      ]);
      IncluyePaquete::create([
        'idincluyepaquete'=>9,
        'incluye_id'=>19,
        'paquete_id'=>3
      ]);
      IncluyePaquete::create([
        'idincluyepaquete'=>10,
        'incluye_id'=>20,
        'paquete_id'=>3
      ]);
      IncluyePaquete::create([
        'idincluyepaquete'=>11,
        'incluye_id'=>21,
        'paquete_id'=>3
      ]);
      IncluyePaquete::create([
        'idincluyepaquete'=>12,
        'incluye_id'=>11,
        'paquete_id'=>4
      ]);
      IncluyePaquete::create([
        'idincluyepaquete'=>13,
        'incluye_id'=>22,
        'paquete_id'=>4
      ]);
      IncluyePaquete::create([
        'idincluyepaquete'=>14,
        'incluye_id'=>23,
        'paquete_id'=>4
      ]);
      IncluyePaquete::create([
        'idincluyepaquete'=>15,
        'incluye_id'=>24,
        'paquete_id'=>4
      ]);
      IncluyePaquete::create([
        'idincluyepaquete'=>16,
        'incluye_id'=>25,
        'paquete_id'=>4
      ]);
      IncluyePaquete::create([
        'idincluyepaquete'=>17,
        'incluye_id'=>27,
        'paquete_id'=>5
      ]);
      IncluyePaquete::create([
        'idincluyepaquete'=>18,
        'incluye_id'=>28,
        'paquete_id'=>5
      ]);
      IncluyePaquete::create([
        'idincluyepaquete'=>19,
        'incluye_id'=>29,
        'paquete_id'=>5
      ]);
      IncluyePaquete::create([
        'idincluyepaquete'=>20,
        'incluye_id'=>30,
        'paquete_id'=>5
      ]);
      IncluyePaquete::create([
        'idincluyepaquete'=>21,
        'incluye_id'=>24,
        'paquete_id'=>5
      ]);
      IncluyePaquete::create([
        'idincluyepaquete'=>22,
        'incluye_id'=>12,
        'paquete_id'=>5
      ]);
      IncluyePaquete::create([
        'idincluyepaquete'=>23,
        'incluye_id'=>32,
        'paquete_id'=>5
      ]);
      IncluyePaquete::create([
        'idincluyepaquete'=>24,
        'incluye_id'=>33,
        'paquete_id'=>6
      ]);
      IncluyePaquete::create([
        'idincluyepaquete'=>25,
        'incluye_id'=>34,
        'paquete_id'=>6
      ]);
      IncluyePaquete::create([
        'idincluyepaquete'=>26,
        'incluye_id'=>35,
        'paquete_id'=>6
      ]);
      IncluyePaquete::create([
        'idincluyepaquete'=>27,
        'incluye_id'=>36,
        'paquete_id'=>6
      ]);
      IncluyePaquete::create([
        'idincluyepaquete'=>28,
        'incluye_id'=>37,
        'paquete_id'=>6
      ]);
      IncluyePaquete::create([
        'idincluyepaquete'=>29,
        'incluye_id'=>38,
        'paquete_id'=>6
      ]);
      IncluyePaquete::create([
        'idincluyepaquete'=>30,
        'incluye_id'=>39,
        'paquete_id'=>6
      ]);
      IncluyePaquete::create([
        'idincluyepaquete'=>31,
        'incluye_id'=>1,
        'paquete_id'=>7
      ]);
      IncluyePaquete::create([
        'idincluyepaquete'=>32,
        'incluye_id'=>2,
        'paquete_id'=>7
      ]);
      IncluyePaquete::create([
        'idincluyepaquete'=>33,
        'incluye_id'=>3,
        'paquete_id'=>7
      ]);
      IncluyePaquete::create([
        'idincluyepaquete'=>34,
        'incluye_id'=>4,
        'paquete_id'=>7
      ]);
      IncluyePaquete::create([
        'idincluyepaquete'=>35,
        'incluye_id'=>5,
        'paquete_id'=>7
      ]);
      IncluyePaquete::create([
        'idincluyepaquete'=>36,
        'incluye_id'=>6,
        'paquete_id'=>7
      ]);
      IncluyePaquete::create([
        'idincluyepaquete'=>37,
        'incluye_id'=>7,
        'paquete_id'=>7
      ]);
      IncluyePaquete::create([
        'idincluyepaquete'=>38,
        'incluye_id'=>8,
        'paquete_id'=>7
      ]);
      IncluyePaquete::create([
        'idincluyepaquete'=>39,
        'incluye_id'=>9,
        'paquete_id'=>7
      ]);
      IncluyePaquete::create([
        'idincluyepaquete'=>40,
        'incluye_id'=>10,
        'paquete_id'=>7
      ]);

    }

}
