<?php

use Illuminate\Database\Seeder;
use App\ItinerarioPaquete as ItinerarioPaquete;
class ItinerarioPaqueteSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      ItinerarioPaquete::create([
        'iditinerariopaquete'=>1,
        'itinerario_id'=>1,
        'paquete_id'=>2
      ]);
      ItinerarioPaquete::create([
        'iditinerariopaquete'=>2,
        'itinerario_id'=>2,
        'paquete_id'=>2
      ]);
      ItinerarioPaquete::create([
        'iditinerariopaquete'=>3,
        'itinerario_id'=>3,
        'paquete_id'=>2
      ]);
      ItinerarioPaquete::create([
        'iditinerariopaquete'=>4,
        'itinerario_id'=>4,
        'paquete_id'=>2
      ]);
      ItinerarioPaquete::create([
        'iditinerariopaquete'=>5,
        'itinerario_id'=>5,
        'paquete_id'=>2
      ]);
      ItinerarioPaquete::create([
        'iditinerariopaquete'=>6,
        'itinerario_id'=>6,
        'paquete_id'=>2
      ]);
      ItinerarioPaquete::create([
        'iditinerariopaquete'=>7,
        'itinerario_id'=>7,
        'paquete_id'=>2
      ]);
      ItinerarioPaquete::create([
        'iditinerariopaquete'=>8,
        'itinerario_id'=>8,
        'paquete_id'=>3
      ]);
      ItinerarioPaquete::create([
        'iditinerariopaquete'=>9,
        'itinerario_id'=>9,
        'paquete_id'=>3
      ]);
      ItinerarioPaquete::create([
        'iditinerariopaquete'=>10,
        'itinerario_id'=>10,
        'paquete_id'=>3
      ]);
      ItinerarioPaquete::create([
        'iditinerariopaquete'=>11,
        'itinerario_id'=>11,
        'paquete_id'=>3
      ]);
      ItinerarioPaquete::create([
        'iditinerariopaquete'=>12,
        'itinerario_id'=>12,
        'paquete_id'=>3
      ]);
      ItinerarioPaquete::create([
        'iditinerariopaquete'=>13,
        'itinerario_id'=>13,
        'paquete_id'=>3
      ]);
      ItinerarioPaquete::create([
        'iditinerariopaquete'=>14,
        'itinerario_id'=>14,
        'paquete_id'=>3
      ]);
      ItinerarioPaquete::create([
        'iditinerariopaquete'=>15,
        'itinerario_id'=>15,
        'paquete_id'=>3
      ]);
      ItinerarioPaquete::create([
        'iditinerariopaquete'=>16,
        'itinerario_id'=>16,
        'paquete_id'=>3
      ]);
      ItinerarioPaquete::create([
        'iditinerariopaquete'=>17,
        'itinerario_id'=>17,
        'paquete_id'=>3
      ]);
      ItinerarioPaquete::create([
        'iditinerariopaquete'=>18,
        'itinerario_id'=>18,
        'paquete_id'=>3
      ]);
      ItinerarioPaquete::create([
        'iditinerariopaquete'=>19,
        'itinerario_id'=>19,
        'paquete_id'=>3
      ]);
      ItinerarioPaquete::create([
        'iditinerariopaquete'=>20,
        'itinerario_id'=>20,
        'paquete_id'=>3
      ]);
      ItinerarioPaquete::create([
        'iditinerariopaquete'=>21,
        'itinerario_id'=>21,
        'paquete_id'=>3
      ]);
      ItinerarioPaquete::create([
        'iditinerariopaquete'=>22,
        'itinerario_id'=>22,
        'paquete_id'=>4
      ]);
      ItinerarioPaquete::create([
        'iditinerariopaquete'=>23,
        'itinerario_id'=>23,
        'paquete_id'=>4
      ]);
      ItinerarioPaquete::create([
        'iditinerariopaquete'=>24,
        'itinerario_id'=>24,
        'paquete_id'=>4
      ]);
      ItinerarioPaquete::create([
        'iditinerariopaquete'=>25,
        'itinerario_id'=>25,
        'paquete_id'=>4
      ]);
      ItinerarioPaquete::create([
        'iditinerariopaquete'=>26,
        'itinerario_id'=>26,
        'paquete_id'=>4
      ]);
      ItinerarioPaquete::create([
        'iditinerariopaquete'=>27,
        'itinerario_id'=>27,
        'paquete_id'=>5
      ]);
      ItinerarioPaquete::create([
        'iditinerariopaquete'=>28,
        'itinerario_id'=>28,
        'paquete_id'=>5
      ]);
      ItinerarioPaquete::create([
        'iditinerariopaquete'=>29,
        'itinerario_id'=>29,
        'paquete_id'=>5
      ]);
      ItinerarioPaquete::create([
        'iditinerariopaquete'=>30,
        'itinerario_id'=>30,
        'paquete_id'=>5
      ]);
      ItinerarioPaquete::create([
        'iditinerariopaquete'=>31,
        'itinerario_id'=>31,
        'paquete_id'=>5
      ]);
      ItinerarioPaquete::create([
        'iditinerariopaquete'=>32,
        'itinerario_id'=>32,
        'paquete_id'=>5
      ]);
      ItinerarioPaquete::create([
        'iditinerariopaquete'=>33,
        'itinerario_id'=>33,
        'paquete_id'=>5
      ]);
      ItinerarioPaquete::create([
        'iditinerariopaquete'=>34,
        'itinerario_id'=>34,
        'paquete_id'=>5
      ]);
      ItinerarioPaquete::create([
        'iditinerariopaquete'=>35,
        'itinerario_id'=>35,
        'paquete_id'=>5
      ]);
      ItinerarioPaquete::create([
        'iditinerariopaquete'=>36,
        'itinerario_id'=>36,
        'paquete_id'=>5
      ]);
      ItinerarioPaquete::create([
        'iditinerariopaquete'=>37,
        'itinerario_id'=>37,
        'paquete_id'=>5
      ]);
      ItinerarioPaquete::create([
        'iditinerariopaquete'=>38,
        'itinerario_id'=>38,
        'paquete_id'=>5
      ]);
      ItinerarioPaquete::create([
        'iditinerariopaquete'=>39,
        'itinerario_id'=>39,
        'paquete_id'=>5
      ]);
      ItinerarioPaquete::create([
        'iditinerariopaquete'=>40,
        'itinerario_id'=>40,
        'paquete_id'=>5
      ]);
      ItinerarioPaquete::create([
        'iditinerariopaquete'=>41,
        'itinerario_id'=>41,
        'paquete_id'=>6
      ]);
      ItinerarioPaquete::create([
        'iditinerariopaquete'=>42,
        'itinerario_id'=>42,
        'paquete_id'=>6
      ]);
      ItinerarioPaquete::create([
        'iditinerariopaquete'=>43,
        'itinerario_id'=>43,
        'paquete_id'=>6
      ]);
      ItinerarioPaquete::create([
        'iditinerariopaquete'=>44,
        'itinerario_id'=>44,
        'paquete_id'=>6
      ]);
      ItinerarioPaquete::create([
        'iditinerariopaquete'=>45,
        'itinerario_id'=>45,
        'paquete_id'=>6
      ]);
      ItinerarioPaquete::create([
        'iditinerariopaquete'=>46,
        'itinerario_id'=>46,
        'paquete_id'=>6
      ]);
      ItinerarioPaquete::create([
        'iditinerariopaquete'=>47,
        'itinerario_id'=>47,
        'paquete_id'=>6
      ]);
      ItinerarioPaquete::create([
        'iditinerariopaquete'=>48,
        'itinerario_id'=>48,
        'paquete_id'=>6
      ]);
      ItinerarioPaquete::create([
        'iditinerariopaquete'=>49,
        'itinerario_id'=>49,
        'paquete_id'=>6
      ]);
      ItinerarioPaquete::create([
        'iditinerariopaquete'=>50,
        'itinerario_id'=>50,
        'paquete_id'=>6
      ]);
      ItinerarioPaquete::create([
        'iditinerariopaquete'=>51,
        'itinerario_id'=>51,
        'paquete_id'=>6
      ]);

    }
}
